import { makeStyles } from "@material-ui/core/styles";
const useStyles = makeStyles((theme) => ({
  Div: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    margin: "auto",
    // textAlign: "center",
  },
  textDiv: {
    width: "100%",
    height: "17%",
    padding: "0%",
  },

  RyP: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 24,
    lineHeight: "150%",
    color: "#333333",
    marginTop: 22,
  },
  form: {
    width: "100%",
    height: "76%",
    marginTop: 27,
  },
  form_pass_label: {
    width: "39%",
    height: "6.7%",
    fontFamily: "Roboto",
    fontFtyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "150%",
    margin: 0,
    marginBottom: 7,
    color: "#333333",
  },
  form_pass_input: {
    width: "100%",
    height: "17%",
    marginTop: 0,
    background: "#ffffff",
  },
  form_passRetype_label: {
    width: "39%",
    height: "6.7%",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "150%",
    color: "#333333",
    marginTop: "32px",
    marginBottom: "7px",
  },
  form_passRetype_input: {
    width: "100%",
    height: "17%",
    background: "#ffffff",
  },
  Placeholder: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "150%",
    color: "#acabab",
  },
  buttonStyle: {
    width: "100%",
    height: "16%",
    marginTop: "32px",
    background: "#00b761",
    borderRadius: "10px",
    fontFamily: " Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "150%",
    border: "none",
    color: "#ffffff",
    paddingTop: "14.5px",
    paddingRight: "109px",
    paddingBottom: "14.5px",
    paddingLeft: "109px",
    textTransform: "none",
  },
  linkDiv: {
    position: "relative",
    width: "28.8%", //101,
    height: "6.7%", //21,
    marginTop: "0%",
    marginBottom: "0%",
  },
  arrowIcon: {
    width: "7.2%",
    height: "63.8%",
    marginRight: "12.81px",
  },
  form_Back_to_login: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "150%",
    color: "#0d4ba7",
    textDecoration: "none",
    top: "2%",
    width: "80%",
    height: "100%",
  },
}));
export default useStyles;
